---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-ruby-go

inputs:
- name: bosh-src
- name: bats
- name: bosh-deployment
- name: bosh-release
- name: stemcell
- name: bosh-cli
- name: cpi-release
- name: environment

outputs:
- name: director-state

run:
  path: bats/ci/tasks/deploy-director.sh
