---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-ruby-go

inputs:
- name: bats
- name: director-state
- name: bosh-cli

run:
  path: bats/ci/tasks/destroy-director.sh
