---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bats-aws

inputs:
- name: bosh-src
- name: bats
- name: bosh-deployment
- name: bosh-release
- name: stemcell
- name: bosh-cli
- name: cpi-release
- name: environment

outputs:
- name: bats-config

params:
  BOSH_access_key_id: ""
  BOSH_secret_access_key: ""
  BOSH_region: "us-east-1"
  STEMCELL_NAME: ""

run:
  path: bats/ci/tasks/prepare-environment-aws.sh

